# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# Add application configuration variables here, as shown below.
#

ADMIN_NAME: Admin
ADMIN_EMAIL: admin@travelercar.com
ADMIN_PASSWORD: jokercar2013
ROLES: [admin, user, VIP]

MAILER_FROM: "admin@travelercar.com"

FILEPICKER_KEY: "AejWBw1JhTOa65sdi1uuQz"
1N1_USERNAME: "admin@travelercar.com"
1N1_PASSWORD: "jokercar2013"

CATEGORIES:
  - name: "Citadine"
    price: 2000
  - name: "Berline"
    price: 3000
  - name: "Monospace"
    price: 4500
  - name: "Haut de gamme"
    price: 6000

AIRPORTS:
  - name: "Charles de Gaulle"
    city: "Paris"
    country: "France"
  - name: "Paris Orly"
    city: "Paris"
    country: "France"
  - name: "Beauvais Tille"
    city: "Beauvais"
    country: "France"


development:
  HOST: "http://localhost:3000"
  WP_ROOT: "http://localhost:8888/travelercar"
  FACEBOOK_ID: "654796907877180"
  FACEBOOK_SECRET: "c945c7a3479637346d04fff4a32b1916"
  # LEETCHI_TARGET_USER_ID: "334140"
  # FACEBOOK_ID: "293967994067315"
  # FACEBOOK_SECRET: "5ae5a36faca7df95ab3c3f41ffe9a3c0"


integration:
    HOST: "http://travelercar.com"
    WP_ROOT: "http://travelercar.com/wp"
    FACEBOOK_ID: "370298486423058" # TO CHANGE
    FACEBOOK_SECRET: "0a5ede29b2d6f31165b5f3be0f119e52"
    # LEETCHI_TARGET_USER_ID: "334140"

production:
    HOST: "http://travelercar.com"
    WP_ROOT: "http://travelercar.com/wp"
    FACEBOOK_ID: "334219330058004" # TO CHANGE
    FACEBOOK_SECRET: "8486758b62a184d57c249ae0bda71084"
    # FACEBOOK_ID:  "491888870887545" # TO CHANGE
    # FACEBOOK_SECRET:  "05ae32ad87cd14abcb7b85677021dc1f"


# FILEPICKER_KEY: "A68xA26uYSfO6TDJM0Qp3z"