# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
ADMIN_NAME: Admin
ADMIN_EMAIL: admin@travelercar.com
ADMIN_PASSWORD: jokercar2013
ROLES: [admin, user, VIP]

WP_ROOT: "http://travelercar.novacodex.net/wp"
# WP_ROOT: "http://travelercar.com/wp"
MAILER_FROM: "admin@travelercar.com"
1N1_USERNAME: "admin@travelercar.com"
1N1_PASSWORD: "jokercar2013"

CATEGORIES:
  - name: "Citadine"
    price: 2000
  - name: "Berline"
    price: 3000
  - name: "Monospace"
    price: 4500
  - name: "Haut de gamme"
    price: 6000

AIRPORTS:
  - name: "Charles de Gaulle"
    city: "Paris"
    country: "France"
  - name: "Paris Orly"
    city: "Paris"
    country: "France"
  - name: "Beauvais Tille"
    city: "Beauvais"
    country: "France"

FILEPICKER_KEY: "A68xA26uYSfO6TDJM0Qp3z"

development:
  HOST: "localhost:3000"
  FACEBOOK_ID: "293967994067315"
  FACEBOOK_SECRET: "5ae5a36faca7df95ab3c3f41ffe9a3c0"
  LEETCHI_TARGET_USER_ID: "334140"


integration:
    HOST: "travelercar.novacodex.net"
    FACEBOOK_ID: "370298486423058"
    FACEBOOK_SECRET: "0a5ede29b2d6f31165b5f3be0f119e52"
    LEETCHI_TARGET_USER_ID: "334140"

production:
    HOST: "travelercar.novacodex.net"
    FACEBOOK_ID:  "491888870887545" # TO CHANGE
    FACEBOOK_SECRET:  "05ae32ad87cd14abcb7b85677021dc1f"
